export { IconCard } from "./icons/card";
export { IconClose } from "./icons/close";
export { IconExpand } from "./icons/expand";
export { IconGear } from "./icons/gear";
export { IconGraph } from "./icons/graph";
export { IconHistory } from "./icons/history";
export { IconTriangle } from "./icons/triangle";
export { IconBook } from "./menu/book";
export { IconCheck } from "./menu/check";
export { IconCode } from "./menu/code";
export { IconCreditCard } from "./menu/credit-card";
export { IconEarn } from "./menu/earn";
export { IconInfo } from "./menu/info";
export { IconMessage } from "./menu/message";
export { IconPieChart } from "./menu/piechart";
export { IconSquare } from "./menu/square";
export { IconZap } from "./menu/zap";
export { IconDiscord } from "./social/discord";
export { IconGithub } from "./social/github";
export { IconTelegram } from "./social/telegram";
export { IconTwitter } from "./social/twitter";
export const STATIC_SERVER = 'https://static.gearbox.fi';
export const getStatic = (url) => `${STATIC_SERVER}${url}`;
