export * from "./icons/agents";
export * from "./icons/arrowUnderlying";
export * from "./icons/blockScout";
export * from "./icons/chartLine";
export * from "./icons/coins";
export * from "./icons/copy";
export * from "./icons/cover";
export * from "./icons/editPen";
export * from "./icons/etherscan";
export * from "./icons/expand";
export * from "./icons/external";
export * from "./icons/farm";
export * from "./icons/fire";
export * from "./icons/gamepad";
export * from "./icons/history";
export * from "./icons/key";
export * from "./icons/lighting";
export * from "./icons/linkArrow";
export * from "./icons/pending";
export * from "./icons/questionCircle";
export * from "./icons/robotDead";
export * from "./icons/rocket";
export * from "./icons/shield";
export * from "./icons/slidersSimple";
export * from "./icons/successCircle";
export * from "./icons/swap";
export * from "./icons/tiles";
export * from "./icons/voteDown";
export * from "./icons/voteUp";
export * from "./menu/book";
export * from "./menu/code";
export * from "./menu/credit-card";
export * from "./menu/earn";
export * from "./menu/info";
export * from "./menu/message";
export * from "./social/discord";
export * from "./social/github";
export * from "./social/telegram";
export * from "./social/twitter";

export const STATIC_SERVER = "https://static.gearbox.fi";

export const getStatic = (url: string) => `${STATIC_SERVER}${url}`;
